### ISSUE TITLE
Trying to Expose Java Back-end and send manual requests

### ISSUE THREAD

**Issue by Fasust** [devonfw/my-thai-star#315]
**Category: Question**
_Severity: Low_

Hello Everyone,
as I mentioned in issue #314 I am currently building a Flutter front-end for MTS. I want to expose  a version of the back-end so I can make requests to it from my new front-end. 

I exposed the java back-end by editing the root level _docker-compose.yaml_ like this:

````yaml
version: '3'

services:
  reverse-proxy:
    build: 'reverse-proxy/'
    container_name: 'mts_reverse_proxy'
    image: my-thai-star/reverse-proxy:latest
    networks:
      - my-thai-star
    ports:
      - '8081:80'
  angular:
    build: 'angular/'
    container_name: 'mts_angular'
    image: my-thai-star/angular:latest
    networks:
      - my-thai-star
  java:
    build: 'java/'
    container_name: 'mts_java'
    image: my-thai-star/java:latest
    networks:
      - my-thai-star
    ports:
      - '8082:8081' #Edit
networks:
  my-thai-star:
    driver: bridge
````

I can now send a POST requests to the route `http://127.0.0.1:8082/mythaistar/api/services/rest/dishmanagement/v1/dish/search` but I am getting a 403 - forbidden response, even though the [doc says this route should not require any authentication](https://github.com/devonfw/my-thai-star/wiki/java-design#authentication).

Body of Request:
````json
{
  "categories": [],
  "searchBy": "",
  "pageable": {
    "pageSize": 8,
    "pageNumber": 0,
    "sort": [
      {
        "property": "price",
        "direction": "DESC"
      }
    ]
  },
  "maxPrice": null,
  "minLikes": null
}
````

Header of request
````
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://127.0.0.1:8081
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Content-Type: application/json
Date: Thu, 28 Nov 2019 11:40:40 GMT
Expires: 0
Pragma: no-cache
Server: nginx/1.17.5
Transfer-Encoding: chunked
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
````

How could this be? Or is their maybe a better way to expose the back-end that I didn't think of?

Environment: Windows
